/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parallel dual filter: Int32 AND Float64 (bench: age + salary). Zero-copy views + rayon. */
export declare function filterAnd2I32F64(a: Int32Array, b: Float64Array, opA: number, litA: number, opB: number, litB: number): Uint32Array
/** Parallel dual filter: two Int32 columns. */
export declare function filterAnd2I32I32(a: Int32Array, b: Int32Array, opA: number, litA: number, opB: number, litB: number): Uint32Array
/** Parallel gather of f64 values by indices. */
export declare function gatherF64(src: Float64Array, indices: Uint32Array): Float64Array
/** Parallel gather of i32 values by indices. */
export declare function gatherI32(src: Int32Array, indices: Uint32Array): Int32Array
/** Dense equi-join probe: `out[i] = dense[left[i] - r_min]` or -1 if OOB / empty slot. */
export declare function joinProbeDenseI32(leftKeys: Int32Array, dense: Int32Array, rMin: number): Int32Array
/** Semi/anti filter via dense probe. `want_hit=true` → semi, false → anti. */
export declare function joinSemiDenseI32(leftKeys: Int32Array, dense: Int32Array, rMin: number, wantHit: boolean): Uint32Array
export interface GroupSumsOut {
  sums: Float64Array
  counts: Float64Array
  used: Uint8Array
}
/**
 * Parallel dense groupby: one category-code stream + many f64 value columns.
 * Returns concatenated sums `[col0_card | col1_card | ...]`, per-group counts, and used flags.
 */
export declare function groupbySumsF64(codes: Uint32Array, card: number, cols: Array<Float64Array>): GroupSumsOut
/** Parallel string contains → uint8 mask (1 = hit). Copies strings once into Rust. */
export declare function strContains(values: Array<string>, needle: string): Uint8Array
/** Parallel ASCII/Unicode lower — returns new strings (for utf8 materialize). */
export declare function strToLower(values: Array<string>): Array<string>
