/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'columna_native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.android-arm64.node')
          } else {
            nativeBinding = require('@columna/native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'columna_native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@columna/native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'columna_native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@columna/native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'columna_native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@columna/native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'columna_native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@columna/native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'columna_native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./columna_native.darwin-universal.node')
      } else {
        nativeBinding = require('@columna/native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'columna_native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.darwin-x64.node')
          } else {
            nativeBinding = require('@columna/native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'columna_native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.darwin-arm64.node')
          } else {
            nativeBinding = require('@columna/native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'columna_native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./columna_native.freebsd-x64.node')
      } else {
        nativeBinding = require('@columna/native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@columna/native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@columna/native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@columna/native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@columna/native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@columna/native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@columna/native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@columna/native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'columna_native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./columna_native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@columna/native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'columna_native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./columna_native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@columna/native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { filterAnd2I32F64, filterAnd2I32I32, filterAnd2F64F64, argsortF64, argsortI32, groupbyMinmaxF64, gatherF64, gatherI32, joinProbeDenseI32, joinSemiDenseI32, filterF64, argsortMultiF64, uniqueF64, joinBuildDenseI32, groupbySumsF64, strContains, strToLower, parseCsvUnquoted, writeCsvUnquoted } = nativeBinding

module.exports.filterAnd2I32F64 = filterAnd2I32F64
module.exports.filterAnd2I32I32 = filterAnd2I32I32
module.exports.filterAnd2F64F64 = filterAnd2F64F64
module.exports.argsortF64 = argsortF64
module.exports.argsortI32 = argsortI32
module.exports.groupbyMinmaxF64 = groupbyMinmaxF64
module.exports.gatherF64 = gatherF64
module.exports.gatherI32 = gatherI32
module.exports.joinProbeDenseI32 = joinProbeDenseI32
module.exports.joinSemiDenseI32 = joinSemiDenseI32
module.exports.filterF64 = filterF64
module.exports.argsortMultiF64 = argsortMultiF64
module.exports.uniqueF64 = uniqueF64
module.exports.joinBuildDenseI32 = joinBuildDenseI32
module.exports.groupbySumsF64 = groupbySumsF64
module.exports.strContains = strContains
module.exports.strToLower = strToLower
module.exports.parseCsvUnquoted = parseCsvUnquoted
module.exports.writeCsvUnquoted = writeCsvUnquoted
